### Se pone como admin un usuario
PUT http://localhost:3001/api/users/1/admin
Content-Type: application/json

{
  "admin": true
}

### Se deshabilita un usuario
PUT http://localhost:3001/api/users/wcode/disabled
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2llIiwiaWQiOjEsImlhdCI6MTc2MzY1Mjg4MH0.PHeGxZSiH-Jkc7H3gIMKX-ELtBYR5MRlJGwBy6k8TGM

{
  "disabled": true
}